$background = 181118
$onBackground = 695f68
$surface = 181118
$surfaceDim = 181118
$surfaceBright = 3f363f
$surfaceContainerLowest = 130c13
$surfaceContainerLow = 211921
$surfaceContainer = 251d25
$surfaceContainerHigh = 2f272f
$surfaceContainerHighest = 3b323a
$onSurface = cdc0ca
$surfaceVariant = 504350
$onSurfaceVariant = a998a8
$outline = 867786
$outlineVariant = 433643
$inverseSurface = eddee9
$inverseOnSurface = 534a52
$shadow = 000000
$scrim = 000000
$surfaceTint = f7adff
$primary = dc74ee
$primaryDim = 66007a
$onPrimary = 360042
$primaryContainer = 66007a
$onPrimaryContainer = f6aaff
$inversePrimary = a03cb4
$primaryFixed = 841e9a
$primaryFixedDim = 66007a
$onPrimaryFixed = ffe0fe
$onPrimaryFixedVariant = f49fff
$secondary = bf8cc3
$secondaryDim = 532a5a
$onSecondary = 2d0535
$secondaryContainer = 532a5a
$onSecondaryContainer = e9b3ed
$secondaryFixed = 6c4173
$secondaryFixedDim = 532a5a
$onSecondaryFixed = ffe0fe
$onSecondaryFixedVariant = e1ace5
$tertiary = a2a236
$tertiaryDim = 3c3c00
$onTertiary = 191900
$tertiaryContainer = 3c3c00
$onTertiaryContainer = caca5a
$tertiaryFixed = 545400
$tertiaryFixedDim = 3c3c00
$onTertiaryFixed = f0ef7a
$onTertiaryFixedVariant = c3c354
$error = ff7063
$errorDim = ff7063 <# Matugen non ha errorDim di default, usiamo error #>
$onError = 3a0001
$errorContainer = 7b0007
$onErrorContainer = ffb1a8

$term0 = 181118
$term1 = ff7063
$term2 = dc74ee
$term3 = a2a236
$term4 = bf8cc3
$term5 = 66007a
$term6 = 3c3c00
$term7 = cdc0ca

$rosewater = 66007a
$pink = a2a236
$mauve = dc74ee
$red = ff7063
$maroon = 7b0007
$peach = bf8cc3
$yellow = 545400
$green = 841e9a
$blue = 6c4173
$lavender = 3c3c00

$success = a642ba <# O usa un colore specifico se lo hai nel config #>
$onSuccess = f6aaff
$successContainer = 66007a

$text = cdc0ca
$base = 181118
$mantle = 251d25
$crust = 130c13
