# Template generato da Matugen
foreground            #cfc1b3
background            #191209
selection_foreground  #edbd7e
selection_background  #523401
url_color             #d78e00
cursor                #cfc1b3

# Tab bar colors
active_tab_foreground   #191209
active_tab_background   #d78e00
inactive_tab_foreground #ad9a85
inactive_tab_background #524433

# The 16 terminal colors

# black
color0 #191209
color8 #8a7965

# red
color1 #ff7063
color9 #7b0007

# green
color2 #d78e00
color10 #523400

# yellow
color3 #00aada
color11 #003f53

# blue
color4 #c1955b
color12 #523401

# magenta
color5 #915e00
color13 #915e00

# cyan
color6 #523400
color14 #523400

# white
color7 #cfc1b3
color15 #ad9a85
