# Template generato da Matugen
foreground            #cdc0ca
background            #181118
selection_foreground  #e9b3ed
selection_background  #532a5a
url_color             #dc74ee
cursor                #cdc0ca

# Tab bar colors
active_tab_foreground   #181118
active_tab_background   #dc74ee
inactive_tab_foreground #a998a8
inactive_tab_background #504350

# The 16 terminal colors

# black
color0 #181118
color8 #867786

# red
color1 #ff7063
color9 #7b0007

# green
color2 #dc74ee
color10 #66007a

# yellow
color3 #a2a236
color11 #3c3c00

# blue
color4 #bf8cc3
color12 #532a5a

# magenta
color5 #a03cb4
color13 #a03cb4

# cyan
color6 #66007a
color14 #66007a

# white
color7 #cdc0ca
color15 #a998a8
